import Menu from "../Menu";
import Head from "next/head";
const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>
				<Menu />
				<div>{children}</div>
			</div>
		</>
	);
};

export default Layout;
